name: utopia_tui
description: A comprehensive, high-performance Terminal User Interface (TUI) library for Dart that makes building beautiful console applications effortless.
version: 1.0.0
homepage: https://github.com/utopia-dart/utopia-tui

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  dart_console: ^4.1.2
  ansicolor: ^2.0.3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
